spring:
  datasource:
    username: root
    url: jdbc:mysql://192.168.1.102:3306/department_db
    password: sql@2023
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  boot:
    message: '"Hello Department Service updated"'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
