spring:
  datasource:
    username: root
    url: jdbc:mysql://192.168.1.102:3306/employee_db
    password: sql@2023
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  boot:
    message: '"Hello Employee Service v2"'
server:
  port: '8081'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
